language: java
cache:
  directories:
  - $HOME/.m2
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
install:
  - mvn -N io.takari:maven:wrapper
  - chmod u+x mvnw
  - ./mvnw install -DskipTests=true -Dsource.skip=true -Dgpg.skip=true -Dmaven.javadoc.skip=true -B -V
script: ./mvnw test

